Transform: AWS::Serverless-2016-10-31

Resources:
  BasicAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BasicAuthorizer
      CodeUri: .
      Handler: src/authorizer.handler
      Runtime: nodejs18.x
      Policies:
        - AWSLambdaBasicExecutionRole
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/authorizer.ts

Outputs:
  AuthorizerArn:
    Value: !GetAtt BasicAuthorizer.Arn
    Export:
      Name: AuthorizerArn
