Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3

Resources:
  ApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - DELETE
        MaxAge: 600
      StageName: dev

  GetProductsList:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: getProductsList.handler
      Runtime: nodejs18.x
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Products:
          Type: HttpApi
          Properties:
            ApiId: !Ref ApiGateway
            Path: /products
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - getProductsList.ts

  GetProductsById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: getProductsById.handler
      Runtime: nodejs18.x
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Products:
          Type: HttpApi
          Properties:
            ApiId: !Ref ApiGateway
            Path: /products/{productId}
            Method: get
    Connectors:
      WithProductPage:
        Properties:
          Destination:
            Id: !Ref Products
          Permissions:
            - Read
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - getProductsById.ts

  Products:
    Type: AWS::Serverless::SimpleTable
