version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "import"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-whjrs6m0gw9k"
s3_prefix = "import"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
