Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 300

Resources:
  ApiGateway:
    Type: AWS::Serverless::HttpApi
    Connectors:
      ApiToAuthLambdaConnector:
        Properties:
          Destination:
            Type: AWS::Lambda::Function
            Arn: !ImportValue AuthorizerArn
          Permissions:
            - Write
    Properties:
      Auth:
        Authorizers:
          LambdaAuthorizer:
            AuthorizerPayloadFormatVersion: 2.0
            EnableSimpleResponses: true
            FunctionArn: !ImportValue AuthorizerArn
            Identity:
              Headers:
                - authorization
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
        AllowHeaders:
          - authorization
        MaxAge: 600
      StageName: dev

  ImportProductsFile:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs18.x
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3WritePolicy:
            BucketName: !Ref ImportS3Bucket
      Events:
        Products:
          Type: HttpApi
          Properties:
            ApiId: !Ref ApiGateway
            Path: /import
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - index.ts

  ImportFileParser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.importFileParser
      Runtime: nodejs18.x
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Files:
          Type: S3
          Properties:
            Bucket: !Ref ImportS3Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: uploaded/
      Environment:
        Variables:
          SQS_URL: !ImportValue SQSUrl
    Connectors:
      ReadCSVFile:
        Properties:
          Destination:
            Id: ImportS3Bucket
          Permissions:
            - Read
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - index.ts

  ImportS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: www.import.mdvoy.ru
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - PUT
            AllowedOrigins:
              - "*"

  LambdaToSQSConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: ImportFileParser
      Destination:
        Type: AWS::SQS::Queue
        Arn: !ImportValue SQSArn
      Permissions:
        - Write
